version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: noteshelf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRESQL_URL: postgresql://postgres:postgres@postgres:5432/noteshelf
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
