CREATE TABLE IF NOT EXISTS users(
  id VARCHAR(50) PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  username VARCHAR(100),
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  added_at TIMESTAMP NOT NULL DEFAULT NOW() ,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
