// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: books.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (id, title, author, owner_id, s3_key, total_pages)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, author, owner_id, s3_key, total_pages
`

type CreateBookParams struct {
	ID         uuid.UUID `json:"id"`
	Title      string    `json:"title"`
	Author     *string   `json:"author"`
	OwnerID    string    `json:"owner_id"`
	S3Key      string    `json:"s3_key"`
	TotalPages int32     `json:"total_pages"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.OwnerID,
		arg.S3Key,
		arg.TotalPages,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.OwnerID,
		&i.S3Key,
		&i.TotalPages,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books where id=$1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, author, owner_id, s3_key, total_pages FROM books WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.OwnerID,
		&i.S3Key,
		&i.TotalPages,
	)
	return i, err
}

const getBooksByOwnerID = `-- name: GetBooksByOwnerID :many
SELECT books.id, books.title, books.author, books.owner_id, books.s3_key, books.total_pages, reading_progress.current_page, reading_progress.percentage_complete 
FROM books 
LEFT JOIN reading_progress on reading_progress.book_id = books.id
WHERE owner_id = $1
`

type GetBooksByOwnerIDRow struct {
	Book               Book           `json:"book"`
	CurrentPage        *int32         `json:"current_page"`
	PercentageComplete pgtype.Numeric `json:"percentage_complete"`
}

func (q *Queries) GetBooksByOwnerID(ctx context.Context, ownerID string) ([]GetBooksByOwnerIDRow, error) {
	rows, err := q.db.Query(ctx, getBooksByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksByOwnerIDRow
	for rows.Next() {
		var i GetBooksByOwnerIDRow
		if err := rows.Scan(
			&i.Book.ID,
			&i.Book.Title,
			&i.Book.Author,
			&i.Book.OwnerID,
			&i.Book.S3Key,
			&i.Book.TotalPages,
			&i.CurrentPage,
			&i.PercentageComplete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
