// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID             uuid.UUID `json:"id"`
	Title          string    `json:"title"`
	Author         *string   `json:"author"`
	OwnerID        string    `json:"owner_id"`
	S3Key          string    `json:"s3_key"`
	TotalPages     int32     `json:"total_pages"`
	ThumbnailS3Key *string   `json:"thumbnail_s3_key"`
	AddedAt        time.Time `json:"added_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	IsPublic       bool      `json:"is_public"`
}

type BookViewer struct {
	BookID uuid.UUID `json:"book_id"`
	UserID string    `json:"user_id"`
}

type Note struct {
	ID               uuid.UUID  `json:"id"`
	BookID           uuid.UUID  `json:"book_id"`
	UserID           string     `json:"user_id"`
	Content          *string    `json:"content"`
	Color            *string    `json:"color"`
	AddedAt          time.Time  `json:"added_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	ReferenceType    *string    `json:"reference_type"`
	ReferenceDataPdf *uuid.UUID `json:"reference_data_pdf"`
}

type PdfReference struct {
	ID         uuid.UUID `json:"id"`
	PageNumber int16     `json:"page_number"`
	XStart     float32   `json:"x_start"`
	XEnd       *float32  `json:"x_end"`
	YStart     float32   `json:"y_start"`
	YEnd       *float32  `json:"y_end"`
}

type ReadingProgress struct {
	UserID             string    `json:"user_id"`
	BookID             uuid.UUID `json:"book_id"`
	CurrentPage        int32     `json:"current_page"`
	PercentageComplete float64   `json:"percentage_complete"`
	LastReadAt         time.Time `json:"last_read_at"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Username  *string   `json:"username"`
	FirstName *string   `json:"first_name"`
	LastName  *string   `json:"last_name"`
	AddedAt   time.Time `json:"added_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Phone     *string   `json:"phone"`
}

type WaitListEmail struct {
	Email string `json:"email"`
}
