// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID         uuid.UUID `json:"id"`
	Title      string    `json:"title"`
	Author     *string   `json:"author"`
	OwnerID    string    `json:"owner_id"`
	S3Key      string    `json:"s3_key"`
	TotalPages int32     `json:"total_pages"`
}

type ReadingProgress struct {
	UserID             string    `json:"user_id"`
	BookID             uuid.UUID `json:"book_id"`
	CurrentPage        int32     `json:"current_page"`
	PercentageComplete float64   `json:"percentage_complete"`
	LastReadAt         time.Time `json:"last_read_at"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Username  *string   `json:"username"`
	FirstName *string   `json:"first_name"`
	LastName  *string   `json:"last_name"`
	AddedAt   time.Time `json:"added_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Phone     *string   `json:"phone"`
}
