// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notes.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (id, book_id, user_id, content, color, reference_type, reference_data_pdf)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, book_id, user_id, content, color, added_at, updated_at, reference_type, reference_data_pdf
`

type CreateNoteParams struct {
	ID                 uuid.UUID  `json:"id"`
	BookID             uuid.UUID  `json:"book_id"`
	UserID             string     `json:"user_id"`
	Content            *string    `json:"content"`
	Color              *string    `json:"color"`
	ReferenceType      *string    `json:"reference_type"`
	ReferenceDataPdfID *uuid.UUID `json:"reference_data_pdf_id"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.ID,
		arg.BookID,
		arg.UserID,
		arg.Content,
		arg.Color,
		arg.ReferenceType,
		arg.ReferenceDataPdfID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.UserID,
		&i.Content,
		&i.Color,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.ReferenceType,
		&i.ReferenceDataPdf,
	)
	return i, err
}

const createPDFReference = `-- name: CreatePDFReference :one
INSERT INTO pdf_references (id, page_number, x_start, x_end, y_start, y_end)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, page_number, x_start, x_end, y_start, y_end
`

type CreatePDFReferenceParams struct {
	ID         uuid.UUID `json:"id"`
	PageNumber int16     `json:"page_number"`
	XStart     float32   `json:"x_start"`
	XEnd       *float32  `json:"x_end"`
	YStart     float32   `json:"y_start"`
	YEnd       *float32  `json:"y_end"`
}

func (q *Queries) CreatePDFReference(ctx context.Context, arg CreatePDFReferenceParams) (PdfReference, error) {
	row := q.db.QueryRow(ctx, createPDFReference,
		arg.ID,
		arg.PageNumber,
		arg.XStart,
		arg.XEnd,
		arg.YStart,
		arg.YEnd,
	)
	var i PdfReference
	err := row.Scan(
		&i.ID,
		&i.PageNumber,
		&i.XStart,
		&i.XEnd,
		&i.YStart,
		&i.YEnd,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id=$1
`

func (q *Queries) DeleteNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT notes.id, notes.book_id, notes.user_id, notes.content, notes.color, notes.added_at, notes.updated_at, notes.reference_type, notes.reference_data_pdf, pdf_references.id, pdf_references.page_number, pdf_references.x_start, pdf_references.x_end, pdf_references.y_start, pdf_references.y_end
FROM notes 
LEFT JOIN pdf_references on notes.reference_data_pdf = pdf_references.id
WHERE notes.id = $1
LIMIT 1
`

type GetNoteByIDRow struct {
	Note       Note       `json:"note"`
	ID         *uuid.UUID `json:"id"`
	PageNumber *int16     `json:"page_number"`
	XStart     *float32   `json:"x_start"`
	XEnd       *float32   `json:"x_end"`
	YStart     *float32   `json:"y_start"`
	YEnd       *float32   `json:"y_end"`
}

func (q *Queries) GetNoteByID(ctx context.Context, id uuid.UUID) (GetNoteByIDRow, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i GetNoteByIDRow
	err := row.Scan(
		&i.Note.ID,
		&i.Note.BookID,
		&i.Note.UserID,
		&i.Note.Content,
		&i.Note.Color,
		&i.Note.AddedAt,
		&i.Note.UpdatedAt,
		&i.Note.ReferenceType,
		&i.Note.ReferenceDataPdf,
		&i.ID,
		&i.PageNumber,
		&i.XStart,
		&i.XEnd,
		&i.YStart,
		&i.YEnd,
	)
	return i, err
}

const getNotesForBookUser = `-- name: GetNotesForBookUser :many
SELECT notes.id, notes.book_id, notes.user_id, notes.content, notes.color, notes.added_at, notes.updated_at, notes.reference_type, notes.reference_data_pdf, pdf_references.id, pdf_references.page_number, pdf_references.x_start, pdf_references.x_end, pdf_references.y_start, pdf_references.y_end
FROM notes 
LEFT JOIN pdf_references on notes.reference_data_pdf = pdf_references.id
WHERE book_id = $1 and user_id = $2
ORDER BY added_at DESC
`

type GetNotesForBookUserParams struct {
	BookID uuid.UUID `json:"book_id"`
	UserID string    `json:"user_id"`
}

type GetNotesForBookUserRow struct {
	Note       Note       `json:"note"`
	ID         *uuid.UUID `json:"id"`
	PageNumber *int16     `json:"page_number"`
	XStart     *float32   `json:"x_start"`
	XEnd       *float32   `json:"x_end"`
	YStart     *float32   `json:"y_start"`
	YEnd       *float32   `json:"y_end"`
}

func (q *Queries) GetNotesForBookUser(ctx context.Context, arg GetNotesForBookUserParams) ([]GetNotesForBookUserRow, error) {
	rows, err := q.db.Query(ctx, getNotesForBookUser, arg.BookID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotesForBookUserRow
	for rows.Next() {
		var i GetNotesForBookUserRow
		if err := rows.Scan(
			&i.Note.ID,
			&i.Note.BookID,
			&i.Note.UserID,
			&i.Note.Content,
			&i.Note.Color,
			&i.Note.AddedAt,
			&i.Note.UpdatedAt,
			&i.Note.ReferenceType,
			&i.Note.ReferenceDataPdf,
			&i.ID,
			&i.PageNumber,
			&i.XStart,
			&i.XEnd,
			&i.YStart,
			&i.YEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET content=$1, color=$2
WHERE id = $3
RETURNING id, book_id, user_id, content, color, added_at, updated_at, reference_type, reference_data_pdf
`

type UpdateNoteParams struct {
	Content *string   `json:"content"`
	Color   *string   `json:"color"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.Content, arg.Color, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.UserID,
		&i.Content,
		&i.Color,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.ReferenceType,
		&i.ReferenceDataPdf,
	)
	return i, err
}
