// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wait_list.sql

package repository

import (
	"context"
)

const registerWaitListEmail = `-- name: RegisterWaitListEmail :one
INSERT INTO wait_list_emails (email)
VALUES ($1)
RETURNING email
`

func (q *Queries) RegisterWaitListEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, registerWaitListEmail, email)
	err := row.Scan(&email)
	return email, err
}
